[caption=,title="Основные виды разрешённого использования"]
[cols="a"]
|===
- Для индивидуального жилищного строительства (код 2.1)
- Малоэтажная многоквартирная жилая застройка ✱✱✱✱ (код 2.1.1)
- Блокированная жилая застройка (код 2.3)
- Размещение гаражей для собственных нужд (код 2.7.2)
- Коммунальное обслуживание (код 3.1)
- Предоставление коммунальных услуг (код 3.1.1)
- Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱ (код 3.1.2)
- Оказание услуг связи ✱, ✱✱ (код 3.2.3)
- Бытовое обслуживание ✱, ✱✱ (код 3.3)
- Амбулаторно-поликлиническое обслуживание ✱, ✱✱ (код 3.4.1)
- Дошкольное, начальное и среднее общее образование ✱ (код 3.5.1)
- Осуществление религиозных обрядов ✱ (код 3.7.1)
- Амбулаторное ветеринарное обслуживание ✱, ✱✱ (код 3.10.1)
- Магазины ✱, ✱✱ (код 4.4)
- Общественное питание ✱, ✱✱ (код 4.6)
- Обеспечение занятий спортом в помещениях ✱, ✱✱ (код 5.1.2)
- Площадки для занятий спортом (код 5.1.3)
- Обеспечение внутреннего правопорядка ✱ (код 8.3)
- Земельные участки (территории) общего пользования (код 12.0)
- Улично-дорожная сеть (код 12.0.1)
- Благоустройство территории (код 12.0.2)
|===

.Основные виды разрешённого использования
----
- Для индивидуального жилищного строительства (код 2.1)
- Малоэтажная многоквартирная жилая застройка ✱✱✱✱ (код 2.1.1)
- Блокированная жилая застройка (код 2.3)
- Размещение гаражей для собственных нужд (код 2.7.2)
- Коммунальное обслуживание (код 3.1)
- Предоставление коммунальных услуг (код 3.1.1)
- Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱ (код 3.1.2)
- Оказание услуг связи ✱, ✱✱ (код 3.2.3)
- Бытовое обслуживание ✱, ✱✱ (код 3.3)
- Амбулаторно-поликлиническое обслуживание ✱, ✱✱ (код 3.4.1)
- Дошкольное, начальное и среднее общее образование ✱ (код 3.5.1)
- Осуществление религиозных обрядов ✱ (код 3.7.1)
- Амбулаторное ветеринарное обслуживание ✱, ✱✱ (код 3.10.1)
- Магазины ✱, ✱✱ (код 4.4)
- Общественное питание ✱, ✱✱ (код 4.6)
- Обеспечение занятий спортом в помещениях ✱, ✱✱ (код 5.1.2)
- Площадки для занятий спортом (код 5.1.3)
- Обеспечение внутреннего правопорядка ✱ (код 8.3)
- Земельные участки (территории) общего пользования (код 12.0)
- Улично-дорожная сеть (код 12.0.1)
- Благоустройство территории (код 12.0.2)
----

.Основные виды разрешённого использования
****
- Для индивидуального жилищного строительства (код 2.1)
- Малоэтажная многоквартирная жилая застройка ✱✱✱✱ (код 2.1.1)
- Блокированная жилая застройка (код 2.3)
- Размещение гаражей для собственных нужд (код 2.7.2)
- Коммунальное обслуживание (код 3.1)
- Предоставление коммунальных услуг (код 3.1.1)
- Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱ (код 3.1.2)
- Оказание услуг связи ✱, ✱✱ (код 3.2.3)
- Бытовое обслуживание ✱, ✱✱ (код 3.3)
- Амбулаторно-поликлиническое обслуживание ✱, ✱✱ (код 3.4.1)
- Дошкольное, начальное и среднее общее образование ✱ (код 3.5.1)
- Осуществление религиозных обрядов ✱ (код 3.7.1)
- Амбулаторное ветеринарное обслуживание ✱, ✱✱ (код 3.10.1)
- Магазины ✱, ✱✱ (код 4.4)
- Общественное питание ✱, ✱✱ (код 4.6)
- Обеспечение занятий спортом в помещениях ✱, ✱✱ (код 5.1.2)
- Площадки для занятий спортом (код 5.1.3)
- Обеспечение внутреннего правопорядка ✱ (код 8.3)
- Земельные участки (территории) общего пользования (код 12.0)
- Улично-дорожная сеть (код 12.0.1)
- Благоустройство территории (код 12.0.2)
****

[cols="a"]
|===
- Для индивидуального жилищного строительства (код 2.1)
- Малоэтажная многоквартирная жилая застройка ✱✱✱✱ (код 2.1.1)
- Блокированная жилая застройка (код 2.3)
- Размещение гаражей для собственных нужд (код 2.7.2)
- Коммунальное обслуживание (код 3.1)
- Предоставление коммунальных услуг (код 3.1.1)
- Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱ (код 3.1.2)
- Оказание услуг связи ✱, ✱✱ (код 3.2.3)
- Бытовое обслуживание ✱, ✱✱ (код 3.3)
- Амбулаторно-поликлиническое обслуживание ✱, ✱✱ (код 3.4.1)
- Дошкольное, начальное и среднее общее образование ✱ (код 3.5.1)
- Осуществление религиозных обрядов ✱ (код 3.7.1)
- Амбулаторное ветеринарное обслуживание ✱, ✱✱ (код 3.10.1)
- Магазины ✱, ✱✱ (код 4.4)
- Общественное питание ✱, ✱✱ (код 4.6)
- Обеспечение занятий спортом в помещениях ✱, ✱✱ (код 5.1.2)
- Площадки для занятий спортом (код 5.1.3)
- Обеспечение внутреннего правопорядка ✱ (код 8.3)
- Земельные участки (территории) общего пользования (код 12.0)
- Улично-дорожная сеть (код 12.0.1)
- Благоустройство территории (код 12.0.2)
|===




.Вспомогательные виды разрешённого использования
----
- Предоставление коммунальных услуг (код 3.1.1)
* Земельные участки (территории) общего пользования (код 12.0)
----

==== § 2. Жилые зоны

.Цели выделения зоны:
****
- развитие на основе существующих и вновь осваиваемых территорий жилой застройки зон комфортного малоэтажного (до 4 этажей включительно) преимущественно многоквартирного жилья;
- развитие сферы социального и культурно-бытового обслуживания, обеспечивающей потребности жителей указанных территорий в соответствующих среде формах;
- размещение необходимых объектов инженерной и транспортной инфраструктуры.
****


===== Статья 27. Градостроительный регламент зоны застройки индивидуальными жилыми домами и жилыми домами блокированного типа — Ж1

.Цели выделения зоны
[%collapsible]
====
- развитие на основе существующих и вновь осваиваемых территорий малоэтажной жилой застройки зон комфортного жилья, включающих отдельно стоящие индивидуальные (одноквартирные) жилые дома и жилые дома блокированного типа;
- развитие сферы социального и культурно-бытового обслуживания, обеспечивающей потребности жителей указанных территорий;
- создание условий для размещения необходимых объектов инженерной и транспортной инфраструктур.
====

.Заголовок (список определений -- четыре точки)
....
[horizontal]
2.1:: Для индивидуального жилищного строительства
2.1.1:: Малоэтажная многоквартирная жилая застройка ✱✱✱✱
2.3:: Блокированная жилая застройка
2.7.2:: Размещение гаражей для собственных нужд
3.1:: Коммунальное обслуживание
3.1.1:: Предоставление коммунальных услуг
3.1.2:: Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱
3.2.3:: Оказание услуг связи ✱, ✱✱
3.3:: Бытовое обслуживание ✱, ✱✱
3.4.1:: Амбулаторно-поликлиническое обслуживание ✱, ✱✱
3.5.1:: Дошкольное, начальное и среднее общее образование ✱
3.7.1:: Осуществление религиозных обрядов ✱
3.10.1:: Амбулаторное ветеринарное обслуживание ✱, ✱✱
4.4:: Магазины ✱, ✱✱
4.6:: Общественное питание ✱, ✱✱
5.1.2:: Обеспечение занятий спортом в помещениях ✱, ✱✱
5.1.3:: Площадки для занятий спортом
8.3:: Обеспечение внутреннего правопорядка ✱
12.0:: Земельные участки (территории) общего пользования
12.0.1:: Улично-дорожная сеть
12.0.2:: Благоустройство территории
....

.Заголовок (список определений -- четыре равно)
====
[horizontal]
2.1:: Для индивидуального жилищного строительства
2.1.1:: Малоэтажная многоквартирная жилая застройка ✱✱✱✱
2.3:: Блокированная жилая застройка
2.7.2:: Размещение гаражей для собственных нужд
3.1:: Коммунальное обслуживание
3.1.1:: Предоставление коммунальных услуг
3.1.2:: Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱
3.2.3:: Оказание услуг связи ✱, ✱✱
3.3:: Бытовое обслуживание ✱, ✱✱
3.4.1:: Амбулаторно-поликлиническое обслуживание ✱, ✱✱
3.5.1:: Дошкольное, начальное и среднее общее образование ✱
3.7.1:: Осуществление религиозных обрядов ✱
3.10.1:: Амбулаторное ветеринарное обслуживание ✱, ✱✱
4.4:: Магазины ✱, ✱✱
4.6:: Общественное питание ✱, ✱✱
5.1.2:: Обеспечение занятий спортом в помещениях ✱, ✱✱
5.1.3:: Площадки для занятий спортом
8.3:: Обеспечение внутреннего правопорядка ✱
12.0:: Земельные участки (территории) общего пользования
12.0.1:: Улично-дорожная сеть
12.0.2:: Благоустройство территории
====

.Заголовок (список определений -- fenced)
```
[horizontal]
2.1:: Для индивидуального жилищного строительства
2.1.1:: Малоэтажная многоквартирная жилая застройка ✱✱✱✱
2.3:: Блокированная жилая застройка
2.7.2:: Размещение гаражей для собственных нужд
3.1:: Коммунальное обслуживание
3.1.1:: Предоставление коммунальных услуг
3.1.2:: Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱
3.2.3:: Оказание услуг связи ✱, ✱✱
3.3:: Бытовое обслуживание ✱, ✱✱
3.4.1:: Амбулаторно-поликлиническое обслуживание ✱, ✱✱
3.5.1:: Дошкольное, начальное и среднее общее образование ✱
3.7.1:: Осуществление религиозных обрядов ✱
3.10.1:: Амбулаторное ветеринарное обслуживание ✱, ✱✱
4.4:: Магазины ✱, ✱✱
4.6:: Общественное питание ✱, ✱✱
5.1.2:: Обеспечение занятий спортом в помещениях ✱, ✱✱
5.1.3:: Площадки для занятий спортом
8.3:: Обеспечение внутреннего правопорядка ✱
12.0:: Земельные участки (территории) общего пользования
12.0.1:: Улично-дорожная сеть
12.0.2:: Благоустройство территории
```

.Заголовок (список определений -- listing)
----
[horizontal]
2.1:: Для индивидуального жилищного строительства
2.1.1:: Малоэтажная многоквартирная жилая застройка ✱✱✱✱
2.3:: Блокированная жилая застройка
2.7.2:: Размещение гаражей для собственных нужд
3.1:: Коммунальное обслуживание
3.1.1:: Предоставление коммунальных услуг
3.1.2:: Административные здания организаций, обеспечивающих предоставление коммунальных услуг ✱, ✱✱
3.2.3:: Оказание услуг связи ✱, ✱✱
3.3:: Бытовое обслуживание ✱, ✱✱
3.4.1:: Амбулаторно-поликлиническое обслуживание ✱, ✱✱
3.5.1:: Дошкольное, начальное и среднее общее образование ✱
3.7.1:: Осуществление религиозных обрядов ✱
3.10.1:: Амбулаторное ветеринарное обслуживание ✱, ✱✱
4.4:: Магазины ✱, ✱✱
4.6:: Общественное питание ✱, ✱✱
5.1.2:: Обеспечение занятий спортом в помещениях ✱, ✱✱
5.1.3:: Площадки для занятий спортом
8.3:: Обеспечение внутреннего правопорядка ✱
12.0:: Земельные участки (территории) общего пользования
12.0.1:: Улично-дорожная сеть
12.0.2:: Благоустройство территории
----








.Условно разрешённые виды использования
[horizontal]
2.2:: Для ведения личного подсобного хозяйства (приусадебный земельный участок)
2.7.1:: Хранение автотранспорта ✱
3.2.1:: Дома социального обслуживания ✱
3.2.2:: Оказание социальной помощи населению ✱, ✱✱
3.6.1:: Объекты культурно-досуговой деятельности ✱, ✱✱
3.7.2:: Религиозное управление и образование ✱
3.8.1:: Государственное управление ✱, ✱✱
4.5:: Банковская и страховая деятельность ✱, ✱✱
4.9.1.1:: Заправка транспортных средств ✱

.Вспомогательные виды разрешённого использования
[horizontal]
3.1.1:: Предоставление коммунальных услуг
12.0:: Земельные участки (территории) общего пользования

.Вспомогательные виды разрешённого использования
++++
  3.1.1 Предоставление коммунальных услуг
  
  12.0 Земельные участки (территории) общего пользования
++++

[NOTE]
Для объектов капитального строительства, размещаемых на земельных участках с видами разрешённого использования, отмеченными знаками ✱, ✱✱ и ✱✱✱✱ в настоящей статье, устанавливаются дополнительные условия разрешённого строительства, реконструкции объектов капитального строительства


